language: node_js
node_js:
  - 0.8
  - 0.10
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq beanstalkd
  - echo "START=yes" >> /etc/default/beanstalkd
  - sudo service beanstalkd restart
notifications:
  email:
    on_success: always
    on_failure: always

