language: node_js
node_js:
  - 0.10
  - 0.11
matrix:
  allow_failures:
    - node_js: 0.11
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq beanstalkd
  - echo "START=yes" | sudo tee -a /etc/default/beanstalkd > /dev/null
  - sudo service beanstalkd restart
notifications:
  email:
    on_success: always
    on_failure: always

